import EmployeeNavbar from "@/components/EmployeeNavbar"
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function EmployeeLayout({ children }) {
 return (
    <html lang="en">
      <body>
      <EmployeeNavbar
          links={[
            { name: "Burgers", route: "/employee" },
            { name: "Fries", route: "/inventory" },
          ]}
        />
        {children}
      </body>
    </html>
  )
}
